# Use the official PySpark image
FROM bitnami/spark:latest

# Set the working directory
WORKDIR /app

# Copy the consumer script
COPY consumer.py consumer.py

# Run the consumer script with PySpark
CMD ["/opt/bitnami/spark/bin/spark-submit", "--master", "local[*]", "consumer.py"]

